CodingWeekends/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about , name = 'about'),
    path('contact', views.contact, name = 'contact'),
    path('Q1_2017',views.Q1_2017, name = 'Q1_2017'),
    path('Q3_2017',views.Q3_2017, name = 'Q3_2017'),
    path('Q2_2018', views.Q2_2018, name = 'Q2_2018'),
    path('Q2_2018_register', views.Q2_2018_register, name = 'Q2_2018_register'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from bakery.views import BuildableTemplateView

# Create your views here.
def home(request):
    return render(request,'home/home.html',{})

def about(request):
    return render(request,'about/about.html',{})

def contact(request):
    return render(request,'contact/contact.html',{})

def Q1_2017(request):
    return render(request, 'home/Q1_2017.html',{})
def Q3_2017(request):
    return render(request, 'home/Q3_2017.html',{})

def Q2_2018(request):
    return render(request, 'quarters/Q2_2018.html',{})
def Q2_2018_register(request):
    return render(request, 'quarters/Q2_2018_register.html',{})

class HomeView(BuildableTemplateView):
    build_path = 'index.html'
    template_name = 'home/home.html'

class AboutView(BuildableTemplateView):
    build_path = 'about.html'
    template_name = 'about/about.html'

class ContactView(BuildableTemplateView):
    build_path = 'contact.html'
    template_name = 'contact/contact.html'

class Q1_2017_View(BuildableTemplateView):
    build_path = 'Q1_2017.html'
    template_name = 'home/Q1_2017.html'

class Q3_2017_View(BuildableTemplateView):
    build_path = 'Q3_2017.html'
    template_name = 'home/Q3_2017.html'

class Q2_2018_View(BuildableTemplateView):
    build_path = 'Q2_2018.html'
    template_name = 'quarters/Q2_2018.html'

class Q2_2018_Register_View(BuildableTemplateView):
    build_path = 'Q2_2018_register.html'
    template_name = 'quarters/Q2_2018_register.html'

home/templates/about/about.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset='utf-8'>
        <title>Coding Weekends - About</title>
        {% load static %}
        <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
	</head>
	<body>
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="{% url 'home:about' %}" class='nav navLink' id='currentPage'> About </a>
                </div>
                <div class="col">
                    <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
                </div>
                <div class="col">
                    <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
                </div>
            </div>
        </div>	

			<div class="w3-container" style="padding:5% 30%" >
			<a href="https://foothillcs.club/" target="_blank"><img src="{% static 'home/images/full-logo-transparente.png' %}" id="helloLogo"</img></a>
				<h3>Hello there reader,</h3>
				<p>
                    We are the <u><a href="https://foothillcs.club/" target="_blank">Computer Science Club at Foothill College</a></u>. <br/>
                    If you're interested in computer science, come meet us at <strong>room 5607 on Tuesdays from 3:30-5:30 PM</strong>.<br/>
                    During our club meetings we have workshops and encourage people to work on projects.<br/><br/>
                    To see some of the projects members of the club have worked on, make sure to check out our <u><a href="https://github.com/FoothillCSClub" target="_blank">GitHub</a></u>!
				</p>
			</div>

        <footer class="site-footer text-white">
            <span>
                <a href="https://www.facebook.com/cs.foothill" target="_blank">
                    <i class="fa fa-2x fa-facebook-square"></i>
                </a>
                <a href="https://github.com/FoothillCSClub" target="_blank">
                    <i class="fa fa-2x fa-github"></i>
                </a>
            </span>
            <h4 class="footer-text">Made by the <a href="https://foothillcs.club/" target="_blank">Foothill CS Club</a></h4>
        </footer>
	
	</body>

</html>

home/templates/contact/contact.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>Coding Weekends - Contact Us</title>
        {% load static %}
        <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel='stylesheet' type='text/css' href="{% static 'home/css/contact.css' %}"/>
    </head>
    <body>
        <!-- Navbar -->
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
                </div>
                <div class="col">
                    <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
                </div>
                <div class="col">
                    <a href="{% url 'home:contact' %}" class='nav navLink' id='currentPage'> Contact Us </a>
                </div>
            </div>
        </div>

        <div class="w3-container" style="padding:48px 16px">
            <div class="w3-row-padding">
                <div class="w3-col m3">&nbsp;</div>
                <div class="w3-col m6">
                    <form action="https://docs.google.com/forms/d/e/1FAIpQLSfUzgjRfRqB1V9DFwF6JFearj4KRpneceg7XXpPycrj6qy_XQ/formResponse">
                        <p><input type="text" class="w3-input w3-border quantumWizTextinputPaperinputInput exportInput" jsname="YPqjbf" autocomplete="off" tabindex="0" aria-label="Name" aria-describedby="i.desc.739468433 i.err.739468433" name="entry.1830497564" value="" required="" dir="auto" data-initial-dir="auto" data-initial-value="" placeholder="* Name" ></p>
                        <p><input type="email" class="w3-input w3-border quantumWizTextinputPaperinputInput exportInput" jsname="YPqjbf" autocomplete="off" tabindex="0" aria-label="Email" aria-describedby="i.desc.1709808371 i.err.1709808371" name="entry.16205053" value="" required="" dir="auto" data-initial-dir="auto" data-initial-value="" placeholder="* Email"></p>
                        <p><textarea class="w3-input w3-border quantumWizTextinputPapertextareaInput exportTextarea" jsname="YPqjbf" data-rows="1" tabindex="0" aria-label="Message" jscontroller="gZjhIf" jsaction="input:Lg5SV;ti6hGc:XMgOHc;rcuQ6b:WYd;" required="" name="entry.1940883768" dir="auto" data-initial-dir="auto" data-initial-value="" placeholder="* Message" rows="4"></textarea></p>
                        <p>
                            <button class="w3-button w3-black" type="submit">SEND MESSAGE</button>
                        </p>
                    </form>
                </div>
                <div class="w3-col m3">&nbsp;</div>
            </div>
        </div>

        <footer class="site-footer text-white">
            <span>
                <a href="https://www.facebook.com/cs.foothill" target="_blank">
                    <i class="fa fa-2x fa-facebook-square"></i>
                </a>
                <a href="https://github.com/FoothillCSClub" target="_blank">
                    <i class="fa fa-2x fa-github"></i>
                </a>
            </span>
            <h4 class="footer-text">Made by the <a href="https://foothillcs.club/">Foothill CS Club</a></h4>
        </footer>
    </body>
</html>

home/templates/home/2018.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
        </div>
      </div>
    </div>
  </body>
</html>

home/templates/home/Q1_2017.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
        </div>
      </div>
    </div>
  </body>
</html>

home/templates/home/Q3_2017.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
        </div>
      </div>
    </div>
  </body>
</html>

home/templates/home/about.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink' id='currentPage'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
        </div>
      </div>
    </div>
  </body>
</html>

home/templates/home/contact.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/about.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink' id='currentPage'> Contact Us </a>
        </div>
      </div>
    </div>
  </body>
</html>

home/templates/home/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Coding Weekends</title>
    {% load static %}
    <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href="{% static 'home/css/home.css' %}"/>
  </head>


  <!-- Header Info -->


  <body>
    <!-- Navbar -->
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
        </div>
        <div class="col">
          <a href="{% url 'home:home' %}"><img src="{% static 'home/images/CodingWeekend.png' %}" alt="My image" id='logo' class="nav"/></a>
        </div>
        <div class="col">
          <a href="{% url 'home:contact' %}" class='nav navLink'> Contact Us </a>
        </div>
      </div>
    </div>


    <!-- Quarter sections -->
    <div class="container">
      <a href="{% url 'home:Q2_2018'%}">
        <div class="tint Q3_2017 fadeIn">
          <img class="card-img blank" src="{% static 'home/images/2017Q1.jpg' %}" alt="Card image">
          <div class="card-img-overlay">
            <h2 class="card-title quarter fadeIn">Spring Quarter</h2>
            <h1 class="card-title year fadeIn">2018</h1>
          </div>
        </div>
      </a>
      <a href="{% url 'home:Q1_2017'%}">
        <div class="tint Q1_2017 fadeIn">
            <img class="card-img" src="{% static 'home/images/2017Q1.jpg' %}" alt="Fall Quarter 2017">
            <div class="card-img-overlay">
              <h2 class="card-title quarter fadeIn">Fall Quarter</h2>
              <h1 class="card-title year fadeIn">2017</h1>
            </div>
        </div>
      </a>
    </div>
  </body>
  <script src="{% static 'home/js/script.js' %}"></script>
</html>

home/templates/quarters/Q2_2018.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset='utf-8'>
        <title>Coding Weekends - Spring Quarter 2018</title>
        {% load static %}
        <link rel='icon' href="{% static 'home/images/CodingWeekend.png' %}">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans:700" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel='stylesheet' type='text/css' href="{% static 'home/css/home.css' %}"/>
    </head>
    <body>
        <!-- Navbar -->
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="{% url 'home:about' %}" class='nav navLink'> About </a>
                </div>
                <div class="col">
                </div>
                <div class="col">
                    <a href="{% url 'home:contact' %}" class='nav navLink' id='currentPage'> Contact Us </a>
                </div>
            </div>
        </div>

        <header class="intro2 wrapper other-gradient-background">
            <div class="container text-white text-center">
                <div class="text-group intro-content">
                    <div class="logo-wrap">
                        <a href="{% url 'home:home' %}"><img class="logo" src="{% static 'home/images/CodingWeekend.png' %}" alt="CW Logo - full"></a><br/>
                        <span class="h1">Coding Weekend</span>
                    </div>
                    <div class="text-group2">
                        <p>
                            <span class="h3">April 28 - 29, 2018<br/>10 AM to 8 PM</span><br/>
                            <a style="text-decoration: none" href="https://goo.gl/maps/PHvMNZxfcsL2" target="_blank">
                                <span class="h3">4700 building</span>
                                <span class="h3">Foothill College, Los Altos, CA</span>
                            </a>
                        </p>
                    </div>
                    <div class="text-group__ft">
                        <a class="btn" href="{% url 'home:Q2_2018_register' %}">REGISTER</a>
                    </div>
                </div>
            </div>
        </header>

        <div class="container-full text-white text-center gradient-background" id="faq">
            <div class="text-group">
                <div class="logo-wrap">
                    <span class="h1">
                        <span class="bold-header">FAQ</span>
                    </span>
                </div>
                <div class="container-wide">
                    <div class="row2">
                        <div class="row2">
                            <div class="six columns">
                                <h3>WHAT IS CODING WEEKEND?</h3>
                                <p>Coding Weekend is an event organized by the <u><a href="https://foothillcs.club/" target="_blank">Computer Science Club</a></u> at Foothill College.
                                    In this event, people interested in CS will come together
                                    for a weekend of learning, coding and fun. You take care of building. We'll take care of you.</p>
                            </div>
                            <div class="six columns">
                                <h3>WHO CAN ATTEND?</h3>
                                <p>Coding Weekend is open to all those who have an interest in CS, from beginners to coding ninjas.
                                    Be prepared to learn, brainstorm, and build amazing software/hardware.</p>
                            </div>
                        </div>
                        <div class="row2">
                            <div class="six columns">
                                <h3>WHAT IF I DON'T HAVE A TEAM?</h3>
                                <p>If you don’t have a teammate, we’ll hold a team-formation workshop where you can meet
                                    your new best friend. Also, <strong>4 people per team</strong> is the limit.
                                </p>
                            </div>
                            <div class="six columns">
                                <h3>HOW MUCH DOES IT COST?</h3>
                                <p>Coding Weekend is free for all admitted participants. We’ll have WiFi, food and workshops.</p>
                            </div>
                        </div>
                        <div class="row2">
                            <div class="six columns">
                                <h3>WHERE CAN I PARK?</h3>
                                <p>The closest parking lot is <u><a href="https://goo.gl/maps/28oTTzdzRYo" target="_blank">Lot 4</a></u>. Remeber to purchase a
                                    <u><a href="https://foothill.edu/reg/cashier/parking.html">parking permit</a></u>!
                                </p>
                            </div>
                            <div class="six columns">
                                <h3>CAN I STAY OVERNIGHT?</h3>
                                <p>No. The doors will close at 8 PM on each day.</p>
                            </div>
                        </div>
                        <div class="row2">
                            <div class="six columns">
                                <h3>WHAT CAN I BRING?</h3>
                                <p>Your laptop and anything else you need to assist in your project. Code written prior to
                                    the coding weekend will not be authorized to compete for prizes.</p>
                            </div>
                            <div class="six columns">
                                <h3>WILL THERE BE ANY PRIZES?</h3>
                                <p>Yes. During the last couple of hours of Coding Weekend, those who would like to participate
                                    in the competition portion of the event will present to the judges. The judging criteria and
                                    prizes for each category can be found <u><strong><a href="https://docs.google.com/document/d/13V5I9q5Qltah9oKgRBbyNix1buKJSoxUNwmPBBkltkI/edit?usp=sharing" target="_blank">here</a></strong></u>.</p>
                            </div>
                        </div>
                        <div class="row2">
                            <div class="twelve columns">
                                <h3>WHAT IF I HAVE MORE QUESTIONS?</h3>
                                <p>Please feel free to send us a message over on <strong><a href="https://facebook.com/cs.foothill/" target="_blank">Facebook</a></strong>
                                    or send us an email at <strong><a href=“mailto:cs.foothill@gmail.com”>cs.foothill@gmail.com</a></strong>.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-full text-white text-center another-gradient-background" id="schedule">
            <div class="text-group">
                <div class="logo-wrap">
                    <span class="h1">
                        <span class="bold-header">Schedule</span>
                    </span>
                </div>
            </div>

            <div class="row justify-content-center">

                <div class="col-4">
                    <h1>Saturday</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Time</th>
                                <th>Event</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>10:00 AM</td>
                                <td>Check In</td>
                            </tr>
                            <tr>
                                <td>11:00 AM</td>
                                <td>Icebreaker and tech talk</td>
                            </tr>
                            <tr>
                                <td>12:00 PM</td>
                                <td>Team building</td>
                            </tr>
                            <tr>
                                <td>12:30 PM</td>
                                <td>Lunch</td>
                            </tr>
                            <tr>
                                <td>1:00 PM</td>
                                <td>Workshop: Javascript, HTML and CSS </td>
                            </tr>
                            <tr>
                                <td>3:00 PM</td>
                                <td>Workshop: Git and Bash </td>
                            </tr>
                            <tr>
                                <td>4:30 PM</td>
                                <td>Workshop: Python </td>
                            </tr>
                            <tr>
                                <td>6:00 PM</td>
                                <td>Dinner </td>
                            </tr>
                            <tr>
                                <td>8:00 PM</td>
                                <td>Doors close </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-4">
                    <h1>Sunday</h1>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Time</th>
                                <th>Event</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>10:00 AM</td>
                                <td>Doors open</td>
                            </tr>
                            <tr>
                                <td>12:30 PM</td>
                                <td>Lunch</td>
                            </tr>
                            <tr>
                                <td>1:00 PM</td>
                                <td>Workshop: MySQL </td>
                            </tr>
                            <tr>
                                <td>2:30 PM</td>
                                <td>Workshop: Buffer Overflow </td>
                            </tr>
                            <tr>
                                <td>3:30 PM</td>
                                <td>Workshop: APIs in JS </td>
                            </tr>
                            <tr>
                                <td>5:00 PM</td>
                                <td>Presentations and Judging Begin </td>
                            </tr>
                            <tr>
                                <td>6:00 PM</td>
                                <td>Dinner </td>
                            </tr>
                            <tr>
                                <td>7:00 PM</td>
                                <td>Presentations end </td>
                            </tr>
                            <tr>
                                <td>7:30 PM</td>
                                <td>Announcement of winners </td>
                            </tr>
                            <tr>
                                <td>8:00 PM</td>
                                <td>Doors close </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <footer class="site-footer text-white">
            <span>
                <a href="https://www.facebook.com/cs.foothill" target="_blank">
                    <i class="fa fa-2x fa-facebook-square"></i>
                </a>
                <a href="https://github.com/FoothillCSClub" target="_blank">
                    <i class="fa fa-2x fa-github"></i>
                </a>
            </span>
            <h4 class="footer-text">Made by the <a href="https://foothillcs.club/" target="_blank">Foothill CS Club</a></h4>
        </footer>
    </body>
</html>